### ISSUE TITLE
cloudinitのバグ

### ISSUE THREAD

**Issue by h-otter** [n0stack/n0stack#130]
```
version: 1
config:
- type: physical
  name: eth0
  mac_address: 52:54:12:fc:77:4f
  subnets:
  - type: static
    address: 192.168.19.1
    netmask: 255.255.255.248
    gateway: 192.168.19.6
    dns_nameservers:
    - 8.8.8.8
- type: physical
  name: eth1
  mac_address: 52:54:4c:33:f3:2b
  subnets:
  - null
```

こうなる
