### ISSUE TITLE
正しくないsyntaxのyamlをdoしたときの挙動について

### ISSUE THREAD

**Issue by proelbtn** [n0stack/n0stack#145]
以下のようなyamlをn0cli doすると、実行されてしまう。

```yaml
ApplyTeam17LifeNetwork:
        type: Network
        action: ApplyNetwork
        args:
                name: life_90_17
                ipv4_cidr: 192.168.0.0/24
        annotations:
                n0core/provisioning/virtual_machine/vlan_id: "1790"
```

schemaが正しいかどうかをテストする何かがあると幸せになれそう。
