### ISSUE TITLE
nameの末尾にunderscoreがついている場合、getができない

### ISSUE THREAD

**Issue by h-otter** [n0stack/n0stack#148]

**Comment by kyontan** [comment]
Image, BlockStorage, Network, VirtualMachine とも試しましたが再現しませんでした (version 72)

**Comment by kyontan** [comment]
当該の問題は再現しませんでしたが、 `DeleteImage` や `DeleteNetwork` で指定した `name` を prefix に持つリソースが全て削除される現象を確認しました

例えば、以下の yaml を実行すると Image `cirros_` は残ることが期待されますが消えます。 (同様に `cirros_2` などがあっても消える。

```yaml
ApplyImage:
  type: Image
  action: ApplyImage
  args:
    name: cirros

ApplyImage2:
  type: Image
  action: ApplyImage
  args:
    name: cirros_

DeleteImage:
  type: Image
  action: DeleteImage
  args:
    name: cirros
  depends_on:
    - ApplyImage
    - ApplyImage2
```
