### ISSUE TITLE
BlockStorage の名前が長すぎると VMが起動しない

### ISSUE THREAD

**Issue by kyontan** [n0stack/n0stack#156]
#144 に近いけど多分別物?

`VirtualMachine` の `CreateVirtualMachine` に失敗する

```
Task 'CreateVirtualMachine' is failed: got error response: rpc error: code = Internal desc = Failed to BootVirtualMachineRequest: rpc error: cod
e = Internal desc = Failed to CreateVirtualMachineAgent: desc=Failed to attach image 'file:///var/lib/n0core/block_storage/test-blockstorageabcdefghi': err='
Failed to create virtio block device: err='Property 'virtio-blk-device.drive' can't find value 'drive-test-blockstorageabcdefghi'''
```

25文字は大丈夫, 26文字はダメ

```
CreateBlockStorage:
  type: Image
  action: GenerateBlockStorage
  args:
    image_name: cloudimage-ubuntu
    block_storage_name: test-blockstorageabcdefgh
    annotations:
      n0core/provisioning/block_storage/request_node_name: test-01
    request_bytes: 1073741824 # 1GiB
    limit_bytes: 10737418240 # 10GiB
    tag: "18.04"

CreateBlockStorageLongerName:
  type: Image
  action: GenerateBlockStorage
  args:
    image_name: cloudimage-ubuntu
    block_storage_name: test-blockstorageabcdefghi
    annotations:
      n0core/provisioning/block_storage/request_node_name: test-01
    request_bytes: 1073741824 # 1GiB
    limit_bytes: 10737418240 # 10GiB
    tag: "18.04"

CreateVirtualMachine:
  type: VirtualMachine
  action: CreateVirtualMachine
  args:
    name: test-vm
    annotations:
      n0core/provisioning/virtual_machine/request_node_name: test-01
    request_cpu_milli_core: 10
    limit_cpu_milli_core: 1000
    request_memory_bytes: 1073741824 # 1GiB
    limit_memory_bytes: 1073741824 # 1GiB
    block_storage_names:
      - test-blockstorageabcdefgh # pass (25 chars)
      # - test-blockstorageabcdefghi # fails (26 chars)
  depends_on:
    - CreateBlockStorage
    - CreateBlockStorageLongerName
```
