### ISSUE TITLE
DummyTask が欲しい

### ISSUE THREAD

**Issue by kyontan** [n0stack/n0stack#157]
DAGで依存関係を書きやすくするために `DummyTask` が欲しいです。

DAG を使うワークフローエンジンである Airflow には `DummyOperator` として存在します。 https://airflow.apache.org/_modules/airflow/operators/dummy_operator.html

**Comment by h-otter** [comment]
ちょっとairflow詳しくないんで、どういうふうに使うのか想像できないです

具体的に教えてもらっていいですか

**Comment by kyontan** [comment]
例えば多数の Network に依存するVMを多数同時に生成したいときに、多数のNetworkへの依存を取りまとめる `DummyTask` を用意することで `depends_on` が簡略になるのでメンテナンスコスト上メリットがあります。

- - -

DummyTask なし:

```yaml
CreateNetworkA:
  ...
CreateNetworkB:
  ...
CreateNetworkC:
  ...

CreateVMA
  ...
  depends_on:
    - CreateNetworkA
    - CreateNetworkB
    - CreateNetworkC

CreateVMB
  ...
  depends_on:
    - CreateNetworkA
    - CreateNetworkB
    - CreateNetworkC

...
```

DummyTask あり:

```yaml
CreateNetworkA:
  ...
CreateNetworkB:
  ...
CreateNetworkC:
  ...

CreateNetworks:
  type: Dummy
  action: Dummy
  depends_on:
    - CreateNetworkA
    - CreateNetworkB
    - CreateNetworkC

CreateVMA
  ...
  depends_on:
    - CreateNetworks

CreateVMB
  ...
  depends_on:
    - CreateNetworks
```
