### ISSUE TITLE
etcd DataStore で Delete時に対象keyをprefixとするレコードが全部消える

### ISSUE THREAD

**Issue by kyontan** [n0stack/n0stack#158]
`DeleteImage` や `DeleteNetwork` で指定した `name` を prefix に持つリソースが全て削除される。
おそらく意図している挙動ではないと思う。

例えば、以下の yaml を実行すると Image `cirros_` は残ることが期待されますが消えます。 (同様に `cirros_2` などがあっても消える。

```yaml
ApplyImage:
  type: Image
  action: ApplyImage
  args:
    name: cirros

ApplyImage2:
  type: Image
  action: ApplyImage
  args:
    name: cirros_

DeleteImage:
  type: Image
  action: DeleteImage
  args:
    name: cirros
  depends_on:
    - ApplyImage
    - ApplyImage2
```
