### ISSUE TITLE
VirtualMachineNIC にannotationsを指定できるようにしたほうが良い

### ISSUE THREAD

**Issue by h-otter** [n0stack/n0stack#174]
NetworkInterfaceのannotationsは意味を持っているので、VMのNICで指定できるようにしたほうが良い

というかメリットがあるがデメリットはない

**Comment by h-otter** [comment]
fixed on ec00f9d4090bf90f4c9a0ec250d2172e85a983aa

**Comment by h-otter** [comment]
```
cvm1:
  type: VirtualMachine
  action: CreateVirtualMachine
  args:
    name: vm1
    annotations:
      n0core/provisioning/virtual_machine/request_node_name: vm-host1
    request_cpu_milli_core: 10
    limit_cpu_milli_core: 1000
    request_memory_bytes: 1
    limit_memory_bytes: 536870912
    block_storage_names:
      - vm1
    nics:
      - network_name: net
        ipv4_address: 192.168.0.1
        annotations:
          n0core/provisioning/virtual_machine/is_gateway: "true"
    uuid: 056d2ccd-0c4c-44dc-a2c8-39a9d394b51f
    login_username: test
    ssh_authorized_keys:
      - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBITowPn2Ol1eCvXN5XV+Lb6jfXzgDbXyEdtayadDUJtFrcN2m2mjC1B20VBAoJcZtSYkmjrllS06Q26Te5sTYvE= testkey
```
example
